version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recovo-cims
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - '.:/var/www'
    ports:
      - '8000:8000'
    depends_on:
      - db  
    networks:
      - app_network 

  db:
    image: 'mysql:8'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravelpass
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
    networks:
      - app_network  

networks:
  app_network:  

volumes:
  db_data: 
